/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OutgoingRouteImport } from './routes/outgoing'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as IncomingRouteImport } from './routes/incoming'
import { Route as AzizRouteImport } from './routes/aziz'
import { Route as IndexRouteImport } from './routes/index'

const OutgoingRoute = OutgoingRouteImport.update({
  id: '/outgoing',
  path: '/outgoing',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomingRoute = IncomingRouteImport.update({
  id: '/incoming',
  path: '/incoming',
  getParentRoute: () => rootRouteImport,
} as any)
const AzizRoute = AzizRouteImport.update({
  id: '/aziz',
  path: '/aziz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aziz': typeof AzizRoute
  '/incoming': typeof IncomingRoute
  '/inventory': typeof InventoryRoute
  '/outgoing': typeof OutgoingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aziz': typeof AzizRoute
  '/incoming': typeof IncomingRoute
  '/inventory': typeof InventoryRoute
  '/outgoing': typeof OutgoingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aziz': typeof AzizRoute
  '/incoming': typeof IncomingRoute
  '/inventory': typeof InventoryRoute
  '/outgoing': typeof OutgoingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aziz' | '/incoming' | '/inventory' | '/outgoing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aziz' | '/incoming' | '/inventory' | '/outgoing'
  id: '__root__' | '/' | '/aziz' | '/incoming' | '/inventory' | '/outgoing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AzizRoute: typeof AzizRoute
  IncomingRoute: typeof IncomingRoute
  InventoryRoute: typeof InventoryRoute
  OutgoingRoute: typeof OutgoingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/outgoing': {
      id: '/outgoing'
      path: '/outgoing'
      fullPath: '/outgoing'
      preLoaderRoute: typeof OutgoingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incoming': {
      id: '/incoming'
      path: '/incoming'
      fullPath: '/incoming'
      preLoaderRoute: typeof IncomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aziz': {
      id: '/aziz'
      path: '/aziz'
      fullPath: '/aziz'
      preLoaderRoute: typeof AzizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AzizRoute: AzizRoute,
  IncomingRoute: IncomingRoute,
  InventoryRoute: InventoryRoute,
  OutgoingRoute: OutgoingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
