/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarehouseRouteImport } from './routes/warehouse'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BranchesIdRouteImport } from './routes/branches_.$id'
import { Route as AdminsUsersRouteImport } from './routes/admins.users'
import { Route as AdminsUserSalariesRouteImport } from './routes/admins.user-salaries'
import { Route as AdminsRolesRouteImport } from './routes/admins.roles'
import { Route as AdminsProfileRouteImport } from './routes/admins.profile'

const WarehouseRoute = WarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesIdRoute = BranchesIdRouteImport.update({
  id: '/branches_/$id',
  path: '/branches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsUsersRoute = AdminsUsersRouteImport.update({
  id: '/admins/users',
  path: '/admins/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsUserSalariesRoute = AdminsUserSalariesRouteImport.update({
  id: '/admins/user-salaries',
  path: '/admins/user-salaries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsRolesRoute = AdminsRolesRouteImport.update({
  id: '/admins/roles',
  path: '/admins/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsProfileRoute = AdminsProfileRouteImport.update({
  id: '/admins/profile',
  path: '/admins/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/employees': typeof EmployeesRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/shifts': typeof ShiftsRoute
  '/warehouse': typeof WarehouseRoute
  '/admins/profile': typeof AdminsProfileRoute
  '/admins/roles': typeof AdminsRolesRoute
  '/admins/user-salaries': typeof AdminsUserSalariesRoute
  '/admins/users': typeof AdminsUsersRoute
  '/branches/$id': typeof BranchesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/employees': typeof EmployeesRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/shifts': typeof ShiftsRoute
  '/warehouse': typeof WarehouseRoute
  '/admins/profile': typeof AdminsProfileRoute
  '/admins/roles': typeof AdminsRolesRoute
  '/admins/user-salaries': typeof AdminsUserSalariesRoute
  '/admins/users': typeof AdminsUsersRoute
  '/branches/$id': typeof BranchesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/employees': typeof EmployeesRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/shifts': typeof ShiftsRoute
  '/warehouse': typeof WarehouseRoute
  '/admins/profile': typeof AdminsProfileRoute
  '/admins/roles': typeof AdminsRolesRoute
  '/admins/user-salaries': typeof AdminsUserSalariesRoute
  '/admins/users': typeof AdminsUsersRoute
  '/branches_/$id': typeof BranchesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/branches'
    | '/employees'
    | '/finance'
    | '/login'
    | '/orders'
    | '/products'
    | '/shifts'
    | '/warehouse'
    | '/admins/profile'
    | '/admins/roles'
    | '/admins/user-salaries'
    | '/admins/users'
    | '/branches/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/branches'
    | '/employees'
    | '/finance'
    | '/login'
    | '/orders'
    | '/products'
    | '/shifts'
    | '/warehouse'
    | '/admins/profile'
    | '/admins/roles'
    | '/admins/user-salaries'
    | '/admins/users'
    | '/branches/$id'
  id:
    | '__root__'
    | '/'
    | '/branches'
    | '/employees'
    | '/finance'
    | '/login'
    | '/orders'
    | '/products'
    | '/shifts'
    | '/warehouse'
    | '/admins/profile'
    | '/admins/roles'
    | '/admins/user-salaries'
    | '/admins/users'
    | '/branches_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BranchesRoute: typeof BranchesRoute
  EmployeesRoute: typeof EmployeesRoute
  FinanceRoute: typeof FinanceRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  ProductsRoute: typeof ProductsRoute
  ShiftsRoute: typeof ShiftsRoute
  WarehouseRoute: typeof WarehouseRoute
  AdminsProfileRoute: typeof AdminsProfileRoute
  AdminsRolesRoute: typeof AdminsRolesRoute
  AdminsUserSalariesRoute: typeof AdminsUserSalariesRoute
  AdminsUsersRoute: typeof AdminsUsersRoute
  BranchesIdRoute: typeof BranchesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warehouse': {
      id: '/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof WarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches_/$id': {
      id: '/branches_/$id'
      path: '/branches/$id'
      fullPath: '/branches/$id'
      preLoaderRoute: typeof BranchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins/users': {
      id: '/admins/users'
      path: '/admins/users'
      fullPath: '/admins/users'
      preLoaderRoute: typeof AdminsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins/user-salaries': {
      id: '/admins/user-salaries'
      path: '/admins/user-salaries'
      fullPath: '/admins/user-salaries'
      preLoaderRoute: typeof AdminsUserSalariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins/roles': {
      id: '/admins/roles'
      path: '/admins/roles'
      fullPath: '/admins/roles'
      preLoaderRoute: typeof AdminsRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins/profile': {
      id: '/admins/profile'
      path: '/admins/profile'
      fullPath: '/admins/profile'
      preLoaderRoute: typeof AdminsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BranchesRoute: BranchesRoute,
  EmployeesRoute: EmployeesRoute,
  FinanceRoute: FinanceRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  ProductsRoute: ProductsRoute,
  ShiftsRoute: ShiftsRoute,
  WarehouseRoute: WarehouseRoute,
  AdminsProfileRoute: AdminsProfileRoute,
  AdminsRolesRoute: AdminsRolesRoute,
  AdminsUserSalariesRoute: AdminsUserSalariesRoute,
  AdminsUsersRoute: AdminsUsersRoute,
  BranchesIdRoute: BranchesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
